version: 2.1

commands:
  setup-for-go-test:
    description: install golang, get dependencies, check out code 
    steps:
      - run:
          name: install golang
          command: |
            sudo rm -rf /usr/local/go
            wget -c https://dl.google.com/go/go1.15.3.linux-amd64.tar.gz -O - | sudo tar -xz -C /usr/local
      - run:
          name: Get dependencies
          command : go get -v -t -d ./...
      - checkout

jobs:
  lint:
    docker:
      - image: circleci/golang:1.15
    steps:
      - checkout
      - run:
          name: golangci-lint
          command: |
            curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh| sh -s -- -b $(go env GOPATH)/bin v1.23.8
            $(go env GOPATH)/bin/golangci-lint run ./...

  test-core:
    machine: true
    steps:
      - setup-for-go-test
      - run:
          name: Test Gnomock
          command: GOMAXPROCS=2 go test -v -race -cover .
      - run:
          name: Test gnomockd
          command: go test -race -cover -v ./internal/gnomockd -run TestGnomockd

  test-sdk-python:
    machine: true
    steps:
      - checkout
      - run:
          name: Install Python
          command: |
            cd /opt/circleci/.pyenv/plugins/python-build/../.. && git pull && cd -
            pyenv install 3.6.9
            pyenv local 3.6.9
      - run:
          name: Get dependencies
          command: |
            cd sdktest/python
            pip3 install -r requirements.txt
      - run:
          name: Generate python sdk
          command: swagger/bin/generate-python.sh
      - run:
          name: Build docker image
          command: docker build --tag gnomock .
      - run:
          name: Run gnomock
          command: |
            docker run -itd \
              -p 23042:23042 \
              -v /var/run/docker.sock:/var/run/docker.sock \
              -v `pwd`:`pwd` \
              gnomock
      - run:
          name: Test
          command: |
            cd sdktest/python
            python3 -m pytest -n 3 -v -k TestSDK

  test-localstack:
    machine: true
    steps:
      - setup-for-go-test
      - run:
          name: Test preset
          command:  go test -race -cover -v ./preset/localstack/...
      - run:
          name: Test server
          command: go test -race -cover -v ./internal/gnomockd -run TestLocalstack
          
  test-elastic:
    machine: true
    steps:
      - setup-for-go-test
      - run:
          name: Test preset
          command:  go test -cover -v ./preset/elastic/...
      - run:
          name: Test server
          command: go test -v ./internal/gnomockd -run TestElastic

  test-memcached:
    machine: true
    steps:
      - setup-for-go-test
      - run:
          name: Test preset
          command:  go test -race -cover -v ./preset/memcached/...
      - run:
          name: Test server
          command: go test -race -cover -v ./internal/gnomockd -run TestMemcached

workflows:
  build-workflow:
    jobs:
      # - lint
      # - test-core
      - test-sdk-python
      # - test-localstack
      # - test-elastic
      # - test-memcached
